name: SlimeBroadcast
version: '${project.version}'
main: me.zazkkya.slimebroadcast.main
api-version: 1.16
authors: [ zAzkkya ]
website: https://github.com/zAzkkya/SlimeBroadcast
commands:
  broadcast:
    description: Send a message to everyone
    usage: /<command>
    aliases:
      - sb
      - slimeb
      - sbroadcast
      - slimebroadcast
    permission: slimebroadcast.use
    permission-message: §e[§abroadcast§e] &cYou don't have permission to use this
    permissions:
      slimebroadcast.use:
        default: op
  sbreload:
    description: Reload config
    usage: /<command>
    aliases:
      - sbr
      - sbreload
      - slimebroadcastreload
    permission: slimebroadcast.reload
    permission-message: §e[§abroadcast§e] §cYou don't have permission to use this
    permissions:
      slimebroadcast.reload:
        default: op
