# ┌─────────────────────────────────────────────────────┐
# |                         ITEM                        |
# |                                                     |
# | Here you can specify what item players should have  |
# |                                                     |
# └─────────────────────────────────────────────────────┘

SlimeHidePlayer:
# Settings of item when all players are visible
itemON: REDSTONE_TORCH_ON 1 0
# Material has format <material> <Total> <data>
# Material is spigot material Find it here: (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)

# Settings of item when all players are hidden
itemOFF: LEVER 1 0
# Material has format <material> <Total> <data>
# Material is spigot material Find it here: (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)

# What slot should Hide item be? (Starts at 1 & ends at 9)
slot: 1

# TimeDelay in seconds
timeDelay: 5

# ┌───────────────────────────────────────────────┐
# |                     MESSAGES                  |
# |                                               |
# | Customize messages that SlimeHidePlayer sends |
# |                                               |
# └───────────────────────────────────────────────┘

messages:
# Messages send when player hides / shows all players
displayNameON: '&f&lHide &a&lPlayers &f&l> &aAll players are now visible!'
displayNameOFF: '&f&lHide &a&lPlayers &f&l> &cAll players are now hidden!'

# %time% can be used to show how many seconds are left until command / item can be used again
consoleDeny: "&cYou cannot execute commands from console!"
visibilityActivated: "&f&lHide &a&lPlayers &f&l> &7You have toggled player visibility: &2on"
visibilityDeactivated: "&f&lHide &a&lPlayers &f&l> &7You have toggled player visibility: &4off"
delay: "&f&lHide &a&lPlayers &f&l> &cPlease wait &4%time% &cseconds before using the Torch!"
noPerm: "&f&lHide &a&lPlayers &f&l> &cYou don't have the permission to to this!"
invalidCmd: "&f&lHide &a&lPlayers &f&l> &cYou typed an invalid command."
configReloaded: "&f&lHide &a&lPlayers &f&l> &2Successfully reloaded config!"
displayNameSet: "&f&lHide &a&lPlayers &f&l> &2Display name %type% set to &8» %args%"
messageSet: "&f&lHide &a&lPlayers &f&l> &2Message %type% set to &8» %args%"

# ┌─────────────────────────────────┐
# |              OTHER              |
# |                                 |
# | Other  SlimeHidePlayer settings |
# |                                 |
# └─────────────────────────────────┘

# This is the world where the player gets the toggler
worldToGetItem:
  world: world

# The worlds where the plugin is enabled. ex: if a player has players disabled and joins world he will not see the players.
enabledWorlds:
  - world
  - hub

miscellaneous:
  #On join, the player gets the torch
  joinTorch: true